version: '2'
services:

  es-node-chatbot:
    image: es-node-chatbot
    container_name: es-node-chatbot
    ports:
      - 3001:3000
    networks:
      - es-node-chatbot

  es-node-chatbot-elasticsearch:
    build: es-node-chatbot-elasticsearch
    container_name: es-node-chatbot-elasticsearch
    extends:
      file: elasticsearch.yml
      service: es-node-chatbot-elasticsearch
    networks:
      - es-node-chatbot

networks:
  es-node-chatbot:
