version: '2'
services:
    es-node-chatbot-elasticsearch:
        image: es-node-chatbot-elasticsearch:latest
        ports:
            - 9221:9200
            - 9321:9300
        command: -Enetwork.host=0.0.0.0 -Ediscovery.type=single-node
